### ISSUE TITLE
New LanguageTool release 6.4

### ISSUE THREAD

**Issue by lpla** [meyayl/docker-languagetool#29]
Hi.

Just to notify that a new LanguageTool version has been released: https://github.com/languagetool-org/languagetool/blob/master/languagetool-standalone/CHANGES.md#64-2024-03-28

**Comment by meyayl** [comment]
Thank you for the reminder. I just pushed the updated image.

**Comment by ovizii** [comment]
It seems the built-in healthcheck is broken. My instance was on "auto-update" and in a restarting frenzy since yesterday when it updated to the new version.

**Comment by meyayl** [comment]
Interesting observation. I am not sure why you experience what you experience.

On my container host it makes no difference whether I use 6.4 or 6.3a-5.

Have you tried setting the environment `LOG_LEVEL` to `DEBUG` to gather more information?

Can you share your compose file, so I can try to reproduce with your exact settings?

**Comment by ovizii** [comment]
Well, let me add a few words before sharing the compose file. I use autoheal, to restart unhealthy containers. When the healthcheck of LanguageTool broke, autoheal continued restarting it. 

I tried disabling the healthcheck with:

```
    healthcheck:
      test: ["NONE"]
```

Which did the trick, except it was stuck on 100% CPU and wasn't working o I went back to meyay/LanguageTool:6.3a-5 and all is perfectly working again. 

I will gladly try with the log-level set to debug this evening and report back. Here is my docker-compose.yml in case you can spot something wrong there.

```
services:

  languagetool:
    image: meyay/languagetool:6.3a-5
    container_name: languagetool
    hostname: languagetool
    restart: "no"
    cap_drop:
      - ALL
    cap_add:
      - CAP_SETUID
      - CAP_SETGID
    security_opt:
      - no-new-privileges
    environment:
      - TZ=Europe/Berlin
      - MAP_UID=1000
      - MAP_GID=1000
      - JAVA_XMS=256m  # OPTIONAL: Setting a minimal Java heap size of 256 mib
      - JAVA_XMX=3G  # OPTIONAL: Setting a maximum Java heap size of 3 Gib
      - download_ngrams_for_langs=en,de
      - langtool_languageModel=/ngrams
      - langtool_fasttextModel=/fasttext/lid.176.bin
      - langtool_pipelinePrewarming=true
      - langtool_pipelineCaching=true
      - langtool_maxPipelinePoolSize=500 # no clue about optimal value
      - langtool_pipelineExpireTimeInSeconds=3600 # no clue about optimal value
#      - langtool_maxWorkQueueSize=50 # no clue about optimal value
      - langtool_cacheSize=500 # size of internal cache in number of sentences (optional, default: 0)
#      - langtool_maxTextLength=50000 # no clue about optimal value
      - langtool_maxCheckThreads=4 # 10 are default, maybe try 2x CPU cores
    networks:
      languagetool:
        ipv4_address: 192.168.192.22
      traefik_languagetool:
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_languagetool"
      - "traefik.http.routers.languagetool.tls=true"
      - "traefik.http.routers.languagetool.entrypoints=websecure"
      - "traefik.http.routers.languagetool.rule=Host(`lang.mydomain.tld`)"
      - "traefik.http.routers.languagetool.middlewares=secHeaders@file"
      - "traefik.http.routers.languagetool.service=languagetool"
      - "traefik.http.services.languagetool.loadbalancer.server.port=8010"
    volumes:
      - /opt/languagetool/ngrams:/ngrams
      - /opt/languagetool/fasttext:/fasttext
      - /dev/shm:/tmp
    cpus: 2
    mem_limit: 4G
#    healthcheck:
#      test: ["NONE"]

```
