### ISSUE TITLE
wget: error getting response: Resource temporarily unavailable

### ISSUE THREAD

**Issue by prrw** [meyayl/docker-languagetool#32]
@meyayl 
Hey, I am getting this error. I have provided the UID and GID in the compose file. I am not the root user on my machine. That should not matter or ?
```
pkrawal@aime-std:~/workspace/git/docker-languagetool$ docker compose up
WARN[0000] /home/pkrawal/workspace/git/docker-languagetool/docker-compose.yml: `version` is obsolete
[+] Running 0/0
 ⠋ Container languagetool  Created                                                                                                                                                                                                      0.1s
Attaching to languagetool
languagetool  | INFO: Setting uid for user "languagetool" to 1839.
languagetool  | INFO: Setting gid for group "languagetool" to 100.
languagetool  | INFO: Fixing ownership for ngrams base folder if necessary.
languagetool  | INFO: Fixing ownership for fasttext model file if necessary.
languagetool  | INFO: Downloading "en" ngrams.
languagetool  | Connecting to http-proxy.ifam.fraunhofer.de:81 (172.28.7.84:81)
languagetool  | wget: error getting response: Resource temporarily unavailable
```
This is my compose file.
```
version: "3.8"

services:
  languagetool:
    image: meyay/languagetool:6.4
    container_name: languagetool
    restart: always
    cap_drop:
      - ALL
    cap_add:
      - CAP_SETUID
      - CAP_SETGID
      - CAP_CHOWN
    security_opt:
      - no-new-privileges
    ports:
      # Using default port from the image
      - 8010:8010
    environment:
      # OVERRIDE: comma seperated list of ngram language models to download (if not existing)
      #           Valid languages are "en", "de", "es", "fr" and "nl". Image default: none
      #           example: download_ngrams_for_langs: en,de,es
      download_ngrams_for_langs: en,de
      # OPTIONAL: container path for the ngrams data. Image default: /ngrams
      langtool_languageModel: /ngrams
      # OVERRIDE: container path to the fasttext binary. Image default: /usr/local/bin/fasttext
      # langtool_fasttextBinary: /usr/local/bin/fasttext
      # OPTIONAL: path to the fasttext model. Will be downloaded if not existing
      langtool_fasttextModel:  /fasttext/lid.176.bin
      # OVERRIDE: minimal Java heap size. Image default: 256m
      # JAVA_XMS: 512m
      # OVERRIDE: Maximum Java heap size. Image default: 1g
      # JAVA_XMX: 1g
      # OVERRIDE: Optional: Configure the garbage collector the JVM will use.
      #           Valid options are: SerialGC, ParallelGC, ParNewGC, G1GC, ZGC
      #           Note: ZGC might not work
      # JAVA_GC: SerialGC
      # OVERRIDE: Optional: Set you own custom Java options for the JVM.
      #           Note: This will render the other JAVA_* options useless.
      # JAVA_OPTS:
      # OVERRIDE: Set UID for user languagetool. Image default: 783
      MAP_UID: 1839
      # OVERRIDE: Set GID for group languagetool. Image default: 783
      MAP_GID: 100
    volumes:
      # OPTIONAL: The location of ngrams data on the local machine
      - ./ngrams:/ngrams
      # OPTIONAL: The location of the fasttext model on the local machine
      - ./fasttext:/fasttext
```

Am I doing something wrong ? I have a proxy server but I am able to get internet inside the container. I tried to install packages manually.
